version: "3.1"

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "3423:3423"
    environment:
      PORT: 3423

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SUBDOMAINS: deployernode.duckdns.org
      TOKEN: 9bbb2312-ba4d-4b25-b9a0-960260f43d17
      LOG_FILE: "false"
    restart: unless-stopped
